server/net_proj/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from net_proj import settings
from sniffer.views import home

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("sniffer/", include("sniffer.urls")),
]

server/sniffer/urls.py
from django.urls import include, path
import django_eventstream

from sniffer import views
from sniffer import config

app_name = "sniffer"
urlpatterns = [
    path("", views.index, name="index"),
    path(config.SSE_URL, include(django_eventstream.urls), {"channels": config.SSE_CHANNELS}),
    # user-client
    path("<int:session_id>/show_net_cards/", views.show_net_cards, name="show_net_cards"),
    path("<int:session_id>/show_packets/", views.show_packets, name="show_packets"),
    path("<int:session_id>/delete_session/", views.delete_session, name="delete_session"),
    # monitered client
    path("net_cards/", views.net_cards, name="net_cards"),
    path("sniff_config/", views.sniff_config, name="sniff_config"),
    path("packet/", views.packet, name="packet"),
    path("session_error/", views.session_error, name="session_error"),
    path("sniff_config_feedback/", views.sniff_config_feedback, name="sniff_config_feedback"),

    # only for debug
    # path("test_sse/", views.test_sse, name="test_sse"),
    # path("render_sse/", views.render_sse, name="render_sse"),
    # path("<int:session_id>/test_show_packets/", views.test_show_packets, name="test_show_packets"),
]

server/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-Hans">
  <head>
    <meta charset="utf-8" />
    <!-- good to view on different device -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- keywords for search engine -->
    {% comment %} <meta name="keywords" content="" /> {% endcomment %}
    {% comment %} <meta name="description" content="" /> {% endcomment %}
    <meta name="author" content="Zhu Zhouzheng" />
    <title>网络嗅探器</title>

    <link rel="stylesheet" href="{% static 'plugins/bootstrap-5.3.3-dist/css/bootstrap.min.css' %}" />

    {% block style %}
    {% endblock %}
  </head>

  <body>
    {% include "theme_toggler.html" %}
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}

    {% include "footer.html" %}

    <script src="{% static 'plugins/jquery-3.7.1.min.js' %}"></script>
    {% comment '要单独引用bundle，两个同时引用会冲突' %}{% endcomment %}
    {% comment %} <script src="{% static 'plugins/bootstrap-5.3.3-dist/js/bootstrap.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'plugins/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/color-modes.js' %}"></script>

    {% block script %}
    {% endblock %}
  </body>
</html>

server/templates/footer.html
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24">
        <title>Product</title><circle cx="12" cy="12" r="10" />
        <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
      </svg>
      <small class="d-block mb-3 text-body-secondary">
        &copy;
        2024-11
      </small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li>
          <a class="link-secondary text-decoration-none" href="#">Cool stuff</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Random feature</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Team feature</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Stuff for developers</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Another one</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Last time</a>
        </li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li>
          <a class="link-secondary text-decoration-none" href="#">Resource name</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Resource</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Another resource</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Final resource</a>
        </li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li>
          <a class="link-secondary text-decoration-none" href="#">Business</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Education</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Government</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Gaming</a>
        </li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li>
          <a class="link-secondary text-decoration-none" href="#">Team</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Locations</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Privacy</a>
        </li>
        <li>
          <a class="link-secondary text-decoration-none" href="#">Terms</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

server/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-12">
        <h1>欢迎来到网络嗅探器项目的主页</h1>
      </div>
      <div class="my-3 col-md-6">
        <div class="card border-primary" onclick="window.location.href='{% url 'sniffer:index' %}';" style="cursor: pointer;">
          <div class="card-header">
            <h3 class="card-title mt-2">网络嗅探器</h3>
          </div>
          <div class="card-body">
            <p class="card-text">这是一个用于网络嗅探的Web应用程序，可以显示和分析网络流量信息。</p>
            <p class="card-subtitle mb-2 text-body-secondary">点击前往使用</p>
          </div>
          <img src="{% static 'img/sniffer_example.png' %}" class="card-img-bottom" alt="network sniffer example image" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

server/templates/navbar.html
{% load static %}

<style>
      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

</style>

<header class="sticky-top">
  <nav class="navbar navbar-expand-sm border-bottom bg-body">
    <div class="container-fluid">
      <h3 class="fw-bolder"><a class="navbar-brand" href="#">网络嗅探器</a></h3>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">主页</a></li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'sniffer:index' %}" role="button">网络嗅探器</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/admin/" role="button">管理员页面</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

server/templates/theme_toggler.html
{% load static %}

<style>
      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-border-color: #5a23c8;
      }

      .bi {
        vertical-align: -0.125em;
        fill: currentColor;
      }


</style>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
  <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
  <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
  <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
  <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
  </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
      <use href="#circle-half"></use>
    </svg>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#sun-fill"></use>
        </svg>Light<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#moon-stars-fill"></use>
        </svg>Dark<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <svg class="bi me-2 opacity-50" width="1em" height="1em">
          <use href="#circle-half"></use>
        </svg>Auto<svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
  </ul>
</div>